[task_02] Add task_02
brstu/OOTPISP-2024 pull request #39
Opened 2024-04-25 05:58 UTC by ViktorKhvedorets

2024-04-25 06:02 UTC, Perhewz-Hellcat commented
Привет

2024-04-25 06:03 UTC, Perhewz-Hellcat commented
А зачем у вани код спиздил?

2024-04-25 10:59 UTC, NogameNo-life requested changes

2024-04-25 10:59 UTC, NogameNo-life commented on README.md
> +| 9   | [Хведорец Виктор Сергеевич](https://github.com/ViktorKhvedorets)|[PO-11-220224](./trunk/po0_220224/) |✅ |✅ | | | | |9|52|
```suggestion
| 9   | [Хведорец Виктор Сергеевич](https://github.com/ViktorKhvedorets)|[PO-11-220224](./trunk/po0_220224/) |✅ |✅ | | | | |9|4|
```

2024-04-25 11:36 UTC, Perhewz-Hellcat commented
52

2024-04-25 13:08 UTC, ViktorKhvedorets reviewed
edit readme

2024-04-30 05:40 UTC, NogameNo-life approved these changes

2024-04-30 05:40 UTC, merged